name: Python app
on:
 push:
 workflow_dispatch:

jobs: 
 echo-python-job: 
  runs-on: ubuntu-latest
  steps: 
   - name: Checkout
     uses: actions/checkout@v4.2.2
   - name: Setup Python
     uses: actions/setup-python@v5.4.0
     with:
      python-version: '3.10'
   - run: pip install --upgrade pip
   - run: pip install requirements.txt
   - run: python server.py


    
